### ISSUE TITLE
Finalize of a design direction

### ISSUE THREAD

**Issue by aswinmohanme** [afterflood/help.afterflood.in#1]
I have sketched out a general idea of what the page would look like

https://www.figma.com/file/XdDkCJlQI3uQtECw0yHUwwCt/AfterFlood-Help?node-id=0%3A1

**Comment by aswinmohanme** [comment]
https://www.figma.com/file/XdDkCJlQI3uQtECw0yHUwwCt/AfterFlood-Help?node-id=0%3A1

**Comment by bodhish** [comment]
@aswinmohanme i guess we can move ahead with the wire-frame
